import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface FinancialSummary {
    totalIncome: number;
    totalExpenses: number;
    currentBalance: number;
}

export interface Transaction {
    id: string;
    type: 'income' | 'expense';
    amount: number;
    category: string;
    date: number;
    notes?: string;
}

export const generateFinancialPDF = (
    transactions: Transaction[],
    summary: FinancialSummary
): jsPDF => {
    const doc = new jsPDF();

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('Financial Report - التقرير المالي', 105, 20, { align: 'center' });

    // Date
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const date = new Date().toLocaleDateString('ar-SA', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
    doc.text(date, 105, 28, { align: 'center' });

    // Summary Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary - الملخص', 14, 40);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Current Balance - الرصيد الحالي: SAR ${summary.currentBalance.toFixed(2)}`, 14, 50);
    doc.text(`Total Income - إجمالي الدخل: SAR ${summary.totalIncome.toFixed(2)}`, 14, 58);
    doc.text(`Total Expenses - إجمالي المصروفات: SAR ${summary.totalExpenses.toFixed(2)}`, 14, 66);

    // Transactions Table
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Transactions - المعاملات', 14, 80);

    const tableData = transactions.map(t => [
        new Date(t.date).toLocaleDateString('en-GB'),
        t.type === 'income' ? 'Income - دخل' : 'Expense - مصروف',
        t.category,
        `SAR ${t.amount.toFixed(2)}`,
        t.notes || '-'
    ]);

    autoTable(doc, {
        startY: 85,
        head: [['Date', 'Type', 'Category', 'Amount', 'Notes']],
        body: tableData,
        styles: {
            font: 'helvetica',
            fontSize: 9,
            cellPadding: 3
        },
        headStyles: {
            fillColor: [16, 185, 129], // primary green
            textColor: [255, 255, 255],
            fontStyle: 'bold'
        },
        alternateRowStyles: {
            fillColor: [250, 248, 245] // cream-50
        }
    });

    // Footer
    const pageCount = doc.internal.pages.length - 1;
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
        `Generated by Minasati - منصتي | Page ${pageCount}`,
        105,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
    );

    return doc;
};

export const downloadFinancialPDF = (doc: jsPDF, filename?: string) => {
    const name = filename || `financial_report_${Date.now()}.pdf`;
    doc.save(name);
};
